### ISSUE TITLE
[Failure] TransactionsExample Transactional sink should work, docs, size mismatch

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1051]
https://travis-ci.org/akka/alpakka-kafka/jobs/648614839#L683

```
[info] TransactionsExample:
[info] Transactional sink
[info] - should work *** FAILED *** (10 seconds, 420 milliseconds)
[info]   Vector(ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1581372000329, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 1, CreateTime = 1581372000329, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 2, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 3, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 4, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 5, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 6, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 7, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 8, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 9, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1581372000329, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 1, CreateTime = 1581372000329, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 2, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 3, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 4, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 5, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 6, CreateTime = 1581372000330, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 7, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 8, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-2-173, partition = 0, leaderEpoch = 0, offset = 9, CreateTime = 1581372000331, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10)) had size 20 instead of expected size 10 (TransactionsExample.scala:58)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2707)
[info]   at docs.scaladsl.TransactionsExample$$anonfun$1$$anonfun$apply$2.apply(TransactionsExample.scala:58)
[info]   at docs.scaladsl.TransactionsExample$$anonfun$1$$anonfun$apply$2.apply(TransactionsExample.scala:26)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at docs.scaladsl.TransactionsExample$$anonfun$1.apply(TransactionsExample.scala:26)
[info]   at docs.scaladsl.TransactionsExample$$anonfun$1.apply(TransactionsExample.scala:26)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at docs.scaladsl.DocsSpecBase.withFixture(DocsSpecBase.scala:15)
[info]   at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
[info]   at docs.scaladsl.DocsSpecBase.runTest(DocsSpecBase.scala:15)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[info]   at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:393)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:407)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
[info]   at docs.scaladsl.DocsSpecBase.runTests(DocsSpecBase.scala:15)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1124)
[info]   at docs.scaladsl.DocsSpecBase.org$scalatest$FlatSpecLike$$super$run(DocsSpecBase.scala:15)
[info]   at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[info]   at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[info] 0m  at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
[info]   at docs.scaladsl.DocsSpecBase.org$scalatest$BeforeAndAfterAll$$super$run(DocsSpecBase.scala:15)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at docs.scaladsl.DocsSpecBase.run(DocsSpecBase.scala:15)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:483)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/648783722#L661
