### ISSUE TITLE
[Failure] IntegrationSpec, Kafka connector must not produce any records after send-failure if stage is stopped

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1055]
https://travis-ci.org/akka/alpakka-kafka/jobs/649448357#L871

```
[info] - must not produce any records after send-failure if stage is stopped *** FAILED *** (1 second, 11 milliseconds)
[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(3),Actor[akka://Spec/deadLetters]) after 949 millis
[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:726)
[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:690)
[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:689)
[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:928)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:644)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$20(IntegrationSpec.scala:200)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$19(IntegrationSpec.scala:187)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at akka.kafka.tests.scaladsl.LogCapturing.withFixture(LogCapturing.scala:57)
[info]   at akka.kafka.tests.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:55)
[info]   at akka.kafka.scaladsl.SpecBase.withFixture(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at akka.kafka.scaladsl.SpecBase.akka$kafka$Repeated$$super$runTest(SpecBase.scala:15)
[info]   at akka.kafka.Repeated.run0$1(Repeated.scala:25)
[info]   at akka.kafka.Repeated.runTest(Repeated.scala:29)
[info]   at akka.kafka.Repeated.runTest$(Repeated.scala:23)
[info]   at akka.kafka.scaladsl.SpecBase.runTest(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at akka.kafka.scaladsl.SpecBase.runTests(SpecBase.scala:15)
[info]   at org.scalatest.Suite.run(Suite.scala:1124)
[info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info]   at akka.kafka.testkit.scaladsl.ScalatestKafkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(ScalatestKafkaSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.kafka.scaladsl.SpecBase.org$scalatest$WordSpecLike$$super$run(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at akka.kafka.scaladsl.SpecBase.run(SpecBase.scala:15)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/650817954#L871

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/650817957#L1200

**Comment by ennru** [comment]
https://travis-ci.org/github/akka/alpakka-kafka/jobs/664851460#L1240 in the scheduled build

**Comment by seglo** [comment]
I dug into this test some more because I still saw failures after fetching the update with #1082.  I'm not sure how this test could ever succeed 100% of the time.  When we send a record with `KafkaProducer.send` we hand off control of asynchronously sending the record and any retries that may be required to the producer.  From Alpakka Kafka's PoV once `KafkaProducer.send` returns a future we carry on to produce the next record.  We can enforce that produced messages aren't passed downstream after a failure occurs in `DefaultProducerStage`, but we can't know whether or not the message was actually received by the broker.  This test will assert no messages are received by the broker by consuming the topic we're producing to.

The assumption in this test that a producer property of `MAX_BLOCK_MS_CONFIG` of `1ms` will fail every time is incorrect (at this time).  What appears to happen in the `KafkaProducer` trace logging is that the first several messages will almost always fail, but then sometimes the metadata is returned in time and available for subsequent messages to use to be sent to the broker before the `DefaultProducerStage` ever handles an error.  That's why we only ever see later messages asserted by the consumer.  Here's a log snippet with `KafkaProducer` trace logging enabled that shows this.

```
18:39:14.275 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.276 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Requesting metadata update for partition 0 of topic topic-1-37.
18:39:14.277 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.277 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Requesting metadata update for partition 0 of topic topic-1-37.
18:39:14.279 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.279 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Requesting metadata update for partition 0 of topic topic-1-37.
18:39:14.280 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.280 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Requesting metadata update for partition 0 of topic topic-1-37.
18:39:14.281 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.281 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Requesting metadata update for partition 0 of topic topic-1-37.
18:39:14.282 DEBUG [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic topic-1-37 not present in metadata after 1 ms.
18:39:14.282 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Attempting to append record ProducerRecord(topic=topic-1-37, partition=0, headers=RecordHeaders(headers = [], isReadOnly = true), key=key, value=7, timestamp=null) with callback akka.kafka.internal.DefaultProducerStageLogic$SendCallback@5404f79a to topic topic-1-37 partition 0
18:39:14.282 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Retrying append due to new batch creation for topic topic-1-37 partition 0. The old partition was 0
18:39:14.283 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Waking up the sender since topic topic-1-37 partition 0 is either full or getting a new batch
18:39:14.283 TRACE [efault-dispatcher-13] o.a.k.clients.producer.KafkaProducer  [Producer clientId=producer-20] Attempting to append record ProducerRecord(topic=topic-1-37, partition=0, headers=RecordHeaders(headers = [], isReadOnly = true), key=key, value=8, timestamp=null) with callback akka.kafka.internal.DefaultProducerStageLogic$SendCallback@29725290 to topic topic-1-37 partition 0
...

// streams logging i added to log what was consumed when we expect no messages

18:39:17.432 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 5
18:39:17.432 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 6
18:39:17.433 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 7
18:39:17.433 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 8
18:39:17.433 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 9
18:39:17.433 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 10
18:39:17.433 DEBUG [efault-dispatcher-25] akka.kafka.scaladsl.IntegrationSpec   [msg] Element: 11
[info] - must not produce any records after send-failure if stage is stopped *** FAILED *** (1 second, 564 milliseconds)
...
<-- [akka.kafka.scaladsl.IntegrationSpec: Kafka connector must not produce any records after send-failure if stage is stopped] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(5),Actor[akka://Spec/deadLetters]) after 950 millis)]
```

The question that remains is why this failure all of a sudden popped up on our radar.  Could the producer be timing `MAX_BLOCK_MS_CONFIG` differently in a recent release?  Did we make a change that introduced this issue?

Perhaps this test should instead assert that no messages are passed through downstream in the producer stream after a stage failure occurs, instead of asserting no messages are ever actually produced to the broker.

**Comment by seglo** [comment]
Test has been removed. See #1083 for details.
