### ISSUE TITLE
[Failure] Consumer is not subscribed to any topics or assigned any partitions

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1117]
Test case: "AssignmentSpec: illegal subscriptions should fail the stream for empty subscriptions list"

The consumer fails immediately after start

```
2020-05-14 08:06:46,447 DEBUG [default-dispatcher-4] [a.kafka.internal.KafkaConsumerActor ]  [ca21a] Creating Kafka consumer with akka.kafka.ConsumerSettings(properties=(auto.offset.reset,earliest),(bootstrap.servers,PLAINTEXT://localhost:32773),(enable.auto.commit,false),(group.id,group-0-138),keyDeserializer=Some(org.apache.kafka.common.serialization.StringDeserializer@399bcc75),valueDeserializer=Some(org.apache.kafka.common.serialization.StringDeserializer@399bcc75),pollInterval=50 milliseconds,pollTimeout=50 milliseconds,stopTimeout=10 milliseconds,closeTimeout=20 seconds,commitTimeout=15 seconds,commitRefreshInterval=Duration.Inf,dispatcher=akka.kafka.default-dispatcher,commitTimeWarning=1 second,waitClosePartition=500 milliseconds,metadataRequestTimeout=5 seconds,drainingCheckInterval=30 milliseconds,connectionCheckerSettings=akka.kafka.ConnectionCheckerSettings(enable=false,maxRetries=3,checkInterval=15 seconds,factor=2.0),partitionHandlerWarning=5 secondsenrichAsync=None)

2020-05-14 08:06:46,512 DEBUG [default-dispatcher-3] [a.kafka.internal.KafkaConsumerActor ]  [ca21a] sending failure class java.lang.IllegalStateException to Actor[akka://Spec/system/StreamSupervisor-15/$$g#465146462]

2020-05-14 08:06:46,514 ERROR [default-dispatcher-3] [a.kafka.internal.KafkaConsumerActor ]  [ca21a] Exception when polling from consumer, stopping actor: java.lang.IllegalStateException: Consumer is not subscribed to any topics or assigned any partitions

java.lang.IllegalStateException: Consumer is not subscribed to any topics or assigned any partitions
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1223)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at akka.kafka.internal.KafkaConsumerActor.poll(KafkaConsumerActor.scala:529)
	at akka.kafka.internal.KafkaConsumerActor.commitAndPoll(KafkaConsumerActor.scala:515)
	at akka.kafka.internal.KafkaConsumerActor.akka$kafka$internal$KafkaConsumerActor$$receivePoll(KafkaConsumerActor.scala:499)
	at akka.kafka.internal.KafkaConsumerActor$$anonfun$regularReceive$1.applyOrElse(KafkaConsumerActor.scala:289)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)

```

https://travis-ci.org/github/akka/alpakka-kafka/jobs/686895504#L5453

**Comment by ennru** [comment]
This was not the failure which failed the build.

https://travis-ci.org/github/akka/alpakka-kafka/jobs/686895504#L5475
