### ISSUE TITLE
Broken use of stage actor in TransactionalSubSource

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1214]
This surfaced after the upgrade of the Kafka client to 2.6.0.

```
09:14:17.171 ERROR [efault-dispatcher-12] o.a.k.c.c.i.ConsumerCoordinator       [Consumer clientId=consumer-group-1-52-34, groupId=group-1-52] User provided listener akka.kafka.internal.KafkaConsumerActor$RebalanceListenerImpl failed on invocation of onPartitionsRevoked for partitions [topic-1-50-0]

akka.stream.stage.GraphStageLogic$StageActorRefNotInitializedException: You must first call getStageActor, to initialize the Actors behavior

	at akka.stream.stage.GraphStageLogic.stageActor(GraphStage.scala:1259)
	at akka.kafka.internal.TransactionalSubSource$$anon$6$$anon$7.onRevoke(TransactionalSources.scala:255)
	at akka.kafka.internal.PartitionAssignmentHelpers$Chain.onRevoke(PartitionAssignmentHelpers.scala:94)
	at akka.kafka.internal.KafkaConsumerActor$RebalanceListenerImpl.onPartitionsRevoked(KafkaConsumerActor.scala:804)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsRevoked(ConsumerCoordinator.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onLeavePrepare(ConsumerCoordinator.java:751)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:976)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:895)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2340)
	at akka.kafka.internal.KafkaConsumerActor.postStop(KafkaConsumerActor.scala:477)
```

https://travis-ci.org/github/akka/alpakka-kafka/jobs/733597397#L1167

**Comment by ennru** [comment]
Digging a bit into the logic there it might be that Kafka's `ConsumerRebalanceListener` has slightly changed behaviour and not calls `onRevoke` when stopping the consumer.
The error indicates the `onRevoke` callback is triggered even before the `TransactionalSubSource`'s `preStart` is called.

**Comment by ennru** [comment]
We haven't experienced this error since we sorted out the Kafka container setup.
I'll leave it open for now, but I believe it was a symptom of the other problems.

**Comment by seglo** [comment]
Haven't seen this for awhile. Closing.
