### ISSUE TITLE
Benchmarks fail since Kafka 2.6.0 upgrade

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#1223]
Something is off with the versions in the Benchmarks.

```
08:32:36.823 INFO  [ntainers-lifecycle-1] 🐳 [confluentinc/cp-kafka:5.4.0]      Container confluentinc/cp-kafka:5.4.0 started in PT11.652S
08:32:52.788 ERROR [-thread | producer-1] o.a.kafka.common.utils.KafkaThread    Uncaught exception in thread 'kafka-producer-network-thread | producer-1':
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
	at org.apache.kafka.common.requests.ApiVersionsRequest$Builder.<clinit>(ApiVersionsRequest.java:36)
	at org.apache.kafka.clients.NetworkClient.handleConnections(NetworkClient.java:910)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:555)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:325)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:240)
	at java.lang.Thread.run(Thread.java:748)
```

https://jenkins.akka.io:8498/job/alpakka-kafka-perf-master/1324/consoleFull

**I've disabled the benchmarks until this has been investigated.**

**Comment by ennru** [comment]
This was due to an inconsistent Confluent Platform version which now is fixed in #1224.
