### ISSUE TITLE
`stop-timeout` delays tear-down of consumer if stream itself has failed

### ISSUE THREAD

**Issue by jrudolph** [akka/alpakka-kafka#1228]
It seems the `consumer.stop-timeout` can be used to drain a consumer of messages that have already been read. (I cannot comment on whether that is (still?) useful in general.)

However, the `stop-timeout` seems to be also applied if the stream consuming / committing the messages failed. In that case, it doesn't seem to make sense to further delay the shutdown of the consumer because it will not be able to drain any further messages in any case.

This was observed in Lagom (https://github.com/lagom/lagom/issues/1786) which has retry logic to reestablish a consumer after it failed but the new instance also fails directly because the old instance is still alive with the same `clientId` so this exception is thrown:

```
 > javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=inventory-1
 >     at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
 >     at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
 >     at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
 >     at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
 >     at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
 >     at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
 >     at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62)
 >     at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:797)
 >     at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:617)
 >     at akka.kafka.ConsumerSettings$.createKafkaConsumer(ConsumerSettings.scala:178)
 >     at akka.kafka.ConsumerSettings$.$anonfun$apply$3(ConsumerSettings.scala:94)
 >     at akka.kafka.ConsumerSettings.createKafkaConsumer(ConsumerSettings.scala:573)
 >     at akka.kafka.internal.KafkaConsumerActor.preStart(KafkaConsumerActor.scala:403)
 >     at akka.actor.Actor.aroundPreStart(Actor.scala:548)
 >     at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
 >     at akka.kafka.internal.KafkaConsumerActor.aroundPreStart(KafkaConsumerActor.scala:202)
```

**Comment by ennru** [comment]
After the switch to Akka 2.6 in #1209 the sources can easily distinguish the reason for cancellation/downstream finish and could shut down without any stop timeout in case of errors.

**Comment by ennru** [comment]
The consumer is kept around to allow for more commits to reach the Kafka broker. Even in the case of a stream failure, the commit collector will try to fire off any offsets it has collected already to the consumer.
