### ISSUE TITLE
KafkaContainerCluster start up sometimes times out

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#1269]
The `KafkaContainerCluster` start up will sometimes timeout. Container logging should be available to help troubleshoot.

Ex) 

```
[info]   java.lang.RuntimeException: java.util.concurrent.TimeoutException
[info]   at akka.kafka.testkit.internal.KafkaContainerCluster.start(KafkaContainerCluster.java:170)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster(TestcontainersKafka.scala:78)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster$(TestcontainersKafka.scala:65)
[info]   at akka.kafka.TransactionsSourceSpec.startCluster(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster(TestcontainersKafka.scala:63)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster$(TestcontainersKafka.scala:63)
[info]   at akka.kafka.TransactionsSourceSpec.startCluster(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.scaladsl.TestcontainersKafkaPerClassLike.setUp(TestcontainersKafkaPerClassLike.scala:16)
[info]   at akka.kafka.testkit.scaladsl.TestcontainersKafkaPerClassLike.setUp$(TestcontainersKafkaPerClassLike.scala:15)
[info]   at akka.kafka.TransactionsSourceSpec.setUp(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.internal.TestFrameworkInterface$Scalatest.beforeAll(TestFrameworkInterface.scala:21)
[info]   at akka.kafka.testkit.internal.TestFrameworkInterface$Scalatest.beforeAll$(TestFrameworkInterface.scala:20)
[info]   at akka.kafka.testkit.scaladsl.ScalatestKafkaSpec.beforeAll(ScalatestKafkaSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.kafka.scaladsl.SpecBase.org$scalatest$wordspec$AnyWordSpecLike$$super$run(SpecBase.scala:16)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[info]   at akka.kafka.scaladsl.SpecBase.run(SpecBase.scala:16)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: java.util.concurrent.TimeoutException:
[info]   at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[info]   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[info]   at akka.kafka.testkit.internal.KafkaContainerCluster.start(KafkaContainerCluster.java:145)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster(TestcontainersKafka.scala:78)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster$(TestcontainersKafka.scala:65)
[info]   at akka.kafka.TransactionsSourceSpec.startCluster(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster(TestcontainersKafka.scala:63)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startCluster$(TestcontainersKafka.scala:63)
[info]   at akka.kafka.TransactionsSourceSpec.startCluster(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.scaladsl.TestcontainersKafkaPerClassLike.setUp(TestcontainersKafkaPerClassLike.scala:16)
[info]   at akka.kafka.testkit.scaladsl.TestcontainersKafkaPerClassLike.setUp$(TestcontainersKafkaPerClassLike.scala:15)
[info]   at akka.kafka.TransactionsSourceSpec.setUp(TransactionsSourceSpec.scala:29)
[info]   at akka.kafka.testkit.internal.TestFrameworkInterface$Scalatest.beforeAll(TestFrameworkInterface.scala:21)
[info]   at akka.kafka.testkit.internal.TestFrameworkInterface$Scalatest.beforeAll$(TestFrameworkInterface.scala:20)
[info]   at akka.kafka.testkit.scaladsl.ScalatestKafkaSpec.beforeAll(ScalatestKafkaSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.kafka.scaladsl.SpecBase.org$scalatest$wordspec$AnyWordSpecLike$$super$run(SpecBase.scala:16)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[info]   at akka.kafka.scaladsl.SpecBase.run(SpecBase.scala:16)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by saaryehudai** [comment]
We are experiencing the same issue, is there a way to increase the timeout?
