### ISSUE TITLE
Broker restart leads to no assigned partitions

### ISSUE THREAD

**Issue by EgbertW** [akka/alpakka-kafka#1304]
I have a Akka / Alpakka streaming job that looks like this:

```
                                           /----- Producer.CommitableSink
Consumer.CommitableSource -- (processing) /
                                          \
                                           \------- Commiter.sink
```

The processing involves a HTTP call that may or may not succeed. If it succeeds, the offset is commited. If it fails, the message is forwarded to a different topic and the offset is committed.

The pipeline processes several millions of messages a day, with a significant spike in a specific hour. We've experienced hangs where the consumer stops consuming messages. They usually seem to be related to changes / restarts of the broker at the Kafka provider (Confluent Cloud). In particilar, I noticed it happening when the client is instructed to leave all groups but doesn't get any groups back because the LeaveGroup command fails - see the log below. In all instances of this problem, simply restarting the pipeline solves the problem.

### Versions used 

```
scalaVersion := "2.13.3"
val AkkaVersion = "2.6.10"
val AkkaHttpVersion = "10.2.0"

libraryDependencies += "com.typesafe.akka" %% "akka-stream"          % AkkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-slf4j"           % AkkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-http"            % AkkaHttpVersion
libraryDependencies += "com.typesafe.akka" %% "akka-http-spray-json" % AkkaHttpVersion
libraryDependencies += "com.typesafe.akka" %% "akka-http-caching"    % AkkaHttpVersion
libraryDependencies += "com.typesafe.akka" %% "akka-stream-kafka"    % "2.1.0-M1"
```

Akka version: 2.6.10

### Expected Behavior

Whenever the broker rebalances or restarts, the clients keep working until subscriptions are up and running again. 

### Actual Behavior

After an error rebalancing, consumer stops working

### Relevant logs

```
2021-01-05 09:32:00,752 WARN   o.a.k.c.c.i.ConsumerCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Offset commit failed on partition preingestion-ingestion-5 at offset 115974727: The coordinator is loading and hence can't process requests.
2021-01-05 09:32:00,752 WARN   a.kafka.internal.KafkaConsumerActor postman-actor-system-akka.kafka.default-dispatcher-25 akka://postman-actor-system/system/kafka-consumer-1 - [e64f6] Kafka commit is to be retried, after=71 ms, commitsInProgress=0, cause=org.apache.kafka.common.errors.CoordinatorLoadInProgressException: The coordinator is loading and hence can't process requests.
2021-01-05 09:32:00,774 INFO   o.a.k.c.c.i.ConsumerCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Revoke previously assigned partitions preingestion-ingestion-retry-5, preingestion-ingestion-0, preingestion-ingestion-1, preingestion-ingestion-8, preingestion-ingestion-retry-1, preingestion-ingestion-retry-2, preingestion-ingestion-9, preingestion-ingestion-retry-3, preingestion-ingestion-6, preingestion-ingestion-7, preingestion-ingestion-retry-4, preingestion-ingestion-4, preingestion-ingestion-5, preingestion-ingestion-2, preingestion-ingestion-retry-0, preingestion-ingestion-3
2021-01-05 09:32:00,774 INFO   o.a.k.c.c.i.AbstractCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Member consumer-preingestion-postman-1-3f652b30-3095-4509-872a-d77c8cbd8fa2 sending LeaveGroup request to coordinator b8-pkc-lq8gm.westeurope.azure.confluent.cloud:9092 (id: 2147483639 rack: null) due to the consumer is being closed
2021-01-05 09:32:00,781 ERROR  o.a.k.c.c.i.AbstractCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] LeaveGroup request failed with error: The coordinator is loading and hence can't process requests.
```

### Reproducible Test Case

I'll see if I can wrap something up. As the issue is not reliably reproduced because it depends on Confluent Cloud broker restarts I'll take me some effort to reliably reproduce it in a test case.

**Comment by seglo** [comment]
[We have a test](https://github.com/akka/alpakka-kafka/blob/v2.1.0-M1/tests/src/test/scala/akka/kafka/scaladsl/ReconnectSpec.scala) that asserts the consumer will recover gracefully when a broker is restarted. In your case are all brokers restarting at the same time, or just the broker with the consumer group coordinator?  The Kafka cluster _should_ handle this gracefully (though it may take some time).

The last line in your log snippets describes a group coordinator that is not ready

```
2021-01-05 09:32:00,781 ERROR  o.a.k.c.c.i.AbstractCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] LeaveGroup request failed with error: The coordinator is loading and hence can't process requests.
```

Does this ever correct itself?  Does error get logged again or just once?  Please provide more logs that capture before and after the broker restart.

**Comment by EgbertW** [comment]
@seglo I don't know exactly - Confluent Cloud manages the broker. It could be that all are restarting at the same time.

The issue does not correct itself. The log I posted is the end of it, nothing else happened after several hours while plenty of unconsumed messages were available.

There are hundreds of similar messages above. Scrolling up a bit I see the following exception:

```
2021-01-05 09:31:30,572 WARN   a.kafka.internal.KafkaConsumerActor postman-actor-system-akka.kafka.default-dispatcher-15 akka://postman-actor-system/system/kafka-consumer-1 - [e64f6] Kafka commit is to be retried, after=70 ms, commitsInProgress=0, cause=org.apache.kafka.common.errors.CoordinatorLoadInProgressException: The coordinator is loading and hence can't process requests.
2021-01-05 09:31:30,641 WARN   o.a.k.c.c.i.ConsumerCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Offset commit failed on partition preingestion-ingestion-5 at offset 115974727: The coordinator is loading and hence can't process requests.
2021-01-05 09:31:30,642 WARN   a.kafka.internal.KafkaConsumerActor postman-actor-system-akka.kafka.default-dispatcher-18 akka://postman-actor-system/system/kafka-consumer-1 - [e64f6] Kafka commit is to be retried, after=69 ms, commitsInProgress=0, cause=org.apache.kafka.common.errors.CoordinatorLoadInProgressException: The coordinator is loading and hence can't process requests.
2021-01-05 09:31:30,675 WARN   o.a.k.c.c.i.ConsumerCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Offset commit failed on partition preingestion-ingestion-5 at offset 115974727: The coordinator is loading and hence can't process requests.
2021-01-05 09:31:30,683 ERROR  n.s.preingestion.postman.Postman$   - Exception during stream processing
akka.kafka.CommitTimeoutException: Kafka commit took longer than: 15 seconds (Ask timed out on [Actor[akka://postman-actor-system/system/kafka-consumer-1#1708832195]] after [15000 ms]. Message of type [akka.kafka.internal.KafkaConsumerActor$Internal$Commit]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.)
	at akka.kafka.internal.KafkaAsyncConsumerCommitterRef$$anonfun$sendCommit$2.applyOrElse(CommittableSources.scala:194)
	at akka.kafka.internal.KafkaAsyncConsumerCommitterRef$$anonfun$sendCommit$2.applyOrElse(CommittableSources.scala:192)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedThreadPool$TimingRunnable.run(ExecutorInstrumentation.scala:437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-01-05 09:31:30,693 INFO   o.a.k.clients.producer.KafkaProducer   - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms.
2021-01-05 09:31:30,693 INFO   o.a.k.clients.producer.KafkaProducer   - [Producer clientId=producer-1] Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms.
2021-01-05 09:31:30,694 ERROR  a.k.i.CommittingProducerSinkStage postman-actor-system-akka.actor.default-dispatcher-161 CommittingProducerSinkStage(akka://postman-actor-system) - [f55b6] committing failed with akka.kafka.CommitTimeoutException: Kafka commit took longer than: 15 seconds (Ask timed out on [Actor[akka://postman-actor-system/system/kafka-consumer-1#1708832195]] after [15000 ms]. Message of type [akka.kafka.internal.KafkaConsumerActor$Internal$Commit]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.)
2021-01-05 09:31:30,697 INFO   o.a.k.clients.producer.KafkaProducer   - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms.
2021-01-05 09:31:30,697 INFO   o.a.k.clients.producer.KafkaProducer   - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 60000 ms.
```

**Comment by seglo** [comment]
I took another look at your logs and it looks like a commit timed out after 15 seconds (the default commit timeout defined in Alpakka Kafka).  Some exceptions raised by the Kafka consumer during the commit process can be retried, for example, you see in your logs that the commit is being retried because the coordinator is loading (loading offsets internally to rebuild the group coordinator on a broker).

```
2021-01-05 09:31:30,572 WARN   a.kafka.internal.KafkaConsumerActor postman-actor-system-akka.kafka.default-dispatcher-15 akka://postman-actor-system/system/kafka-consumer-1 - [e64f6] Kafka commit is to be retried, after=70 ms, commitsInProgress=0, cause=org.apache.kafka.common.errors.CoordinatorLoadInProgressException: The coordinator is loading and hence can't process requests.
```

If the total time of a commit (including commit retries) reaches the commit timeout then the stream is failed and all the stages of the stream stop. As part of the stream shutdown the Kafka consumer is closed.

I noticed in your logs the `LeaveGroup` request is sent by the `KafkaConsumer` as a result of the consumer shutting down (calling `KafkaConsumer.close()`):

```
2021-01-05 09:32:00,774 INFO   o.a.k.c.c.i.AbstractCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] Member consumer-preingestion-postman-1-3f652b30-3095-4509-872a-d77c8cbd8fa2 sending LeaveGroup request to coordinator b8-pkc-lq8gm.westeurope.azure.confluent.cloud:9092 (id: 2147483639 rack: null) due to the consumer is being closed
```
but that appears to fail as well:

```
2021-01-05 09:32:00,781 ERROR  o.a.k.c.c.i.AbstractCoordinator   - [Consumer clientId=consumer-preingestion-postman-1, groupId=preingestion-postman] LeaveGroup request failed with error: The coordinator is loading and hence can't process requests.
```

You could increase the commit timeout (`akka.kafka.consumer.commit-timeout`) from 15 seconds, but I have a feeling the reason your app is getting "stuck" is because you're swallowing the exception from the stream shutdown. If you exit your app when the stream shuts down then your app can enter a crash loop cycle (assuming you're using a scheduler, like in K8s), until the group coordinator is available again.

**Comment by EgbertW** [comment]
@seglo thanks for your response. You're probably right - the exception is caught by Akka Streams and then handled by the supervisor, translated into a stop-command. But then the actor system never shuts down.

I thought Alpakka swallowed the exception but it seems the streaming job isn't shutting down properly. I'll look into that. The application is indeed operating in K8s cluster so restart should be automatic on termination. It just needs to actually terminate for that to happen :)

**Comment by seglo** [comment]
Depending on the nature of your app you could also [restart the stream with `RestartSource`](https://doc.akka.io/docs/alpakka-kafka/current/errorhandling.html#restarting-the-stream-with-a-backoff-stage).

**Comment by EgbertW** [comment]
I increased the commit timeout and wrapped the source in a RestartSource, and also made it terminate if everything comes crashing down together at once. Haven't seen this issue since so the problem was in my use of the library, not a bug. Thanks!
