### ISSUE TITLE
Failed: AtLeastOnce

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka-kafka#1616]
https://github.com/akka/alpakka-kafka/actions/runs/4698741175/jobs/8331468745#step:6:190

```
[info] - should map messages one-to-many, and commit in batches *** FAILED *** (10 seconds, 279 milliseconds)
[info]   Vector(ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1681467789917, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 1, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 2, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 3, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 4, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 5, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 6, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 7, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 8, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 9, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 0, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 1, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 2, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 3, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 4, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 5, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 6, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 7, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 8, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 9, CreateTime = 1681467789930, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 10, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 11, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 12, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 13, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 14, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 15, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 16, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 17, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 18, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-2-85, partition = 0, leaderEpoch = 0, offset = 19, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 10, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 1), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 11, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 2), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 12, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 3), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 13, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 4), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 14, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 5), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 15, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 6), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 16, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 7), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 17, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 8), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 18, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 1, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 9), ConsumerRecord(topic = topic-3-86, partition = 0, leaderEpoch = 0, offset = 19, CreateTime = 1681467793170, serialized key size = 3, serialized value size = 2, headers = RecordHeaders(headers = [], isReadOnly = false), key = key, value = 10)) had size 40 instead of expected size 20 (AtLeastOnce.scala:64)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info]   at org.scalatest.matchers.should.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2720)
[info]   at docs.scaladsl.AtLeastOnce.$anonfun$new$2(AtLeastOnce.scala:64)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at docs.scaladsl.AtLeastOnce.$anonfun$new$1(AtLeastOnce.scala:30)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1812)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at docs.scaladsl.DocsSpecBase.withFixture(DocsSpecBase.scala:17)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1810)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1822)
```

**Comment by johanandren** [comment]
https://github.com/akka/alpakka-kafka/actions/runs/4698741175/jobs/8331468840#step:6:268
