### ISSUE TITLE
Kafka Clients Compatible version Akka 2.7.0

### ISSUE THREAD

**Issue by Pokkybeep** [akka/alpakka-kafka#1756]
I have recently upgraded my jdk version from 8 to 17.
Akka 2.7.0

But I am getting following error
java.lang.NoSuchFieldError: DEFAULT_SASL_ENABLED_MECHANISMS
at kafka.server.Defaults$.(KafkaConfig.scala:210)
at kafka.server.KafkaConfig$.(KafkaConfig.scala:686)
at kafka.server.KafkaConfig.(KafkaConfig.scala:897)
at kafka.server.KafkaConfig.(KafkaConfig.scala:899)
at com.github.charithe.kafka.EphemeralKafkaBroker.buildKafkaConfig(EphemeralKafkaBroker.java:233)
at com.github.charithe.kafka.EphemeralKafkaBroker.startBroker(EphemeralKafkaBroker.java:144)
at com.github.charithe.kafka.EphemeralKafkaBroker.start(EphemeralKafkaBroker.java:124)

Can someone help me with compatible versions of kafka with akka 2.7 ?

Older version->
compile group: "com.typesafe.akka", name: "akka-stream-kafka_2.12", version: "0.18"
compile group: 'org.apache.kafka', name: 'kafka-clients', version: '1.0.0'
compile group: 'com.github.charithe', name: 'kafka-junit', version: '4.0.0'

New->
implementation group: "com.typesafe.akka", name: "akka-stream-kafka_2.12", version: "4.0.2"
implementation group: 'org.apache.kafka', name: 'kafka-clients', version: '3.7.1'
implementation group: 'com.github.charithe', name: 'kafka-junit', version: '4.1.0'

@johanandren  @ennru @efgpinto @patriknw

**Comment by ennru** [comment]
Hej Kavita,

Please refer to the Akka 22.10 release blog for the base versions of Akka libraries that go with Akka 2.7.0.

Also note that the current version of Akka is 24.05 as listed in the other blog posts.
