### ISSUE TITLE
IntegrationSpec: must resume consumer from committed offset

### ISSUE THREAD

**Issue by raboof** [akka/alpakka-kafka#400]
This test failed on Travis:
```
[info] IntegrationSpec:
[info] Reactive kafka streams
[info] - must produce to plainSink and consume from plainSource
[info] - must resume consumer from committed offset *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(36)
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:401)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:890)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.$anonfun$expectNextN$1(StreamTestKit.scala:387)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[info]   ...
```

A lot of logging was produced but it's hard to see what logging belongs to this test... see https://travis-ci.org/akka/reactive-kafka/jobs/333984923

**Comment by 2m** [comment]
https://travis-ci.org/akka/reactive-kafka/jobs/380145783

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
