### ISSUE TITLE
Failed: Transactions should commit the current transaction at commit interval

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#462]
```
14:50:46.456 ERROR akka.actor.RepointableActorRef - Error in stage [akka.kafka.internal.ProducerStage$TransactionProducerStage@165fd214]: Cannot pull port (messages(1699878757)) twice
java.lang.IllegalArgumentException: Cannot pull port (messages(1699878757)) twice
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:466)
	at akka.stream.stage.GraphStageLogic.tryPull(GraphStage.scala:480)
	at akka.kafka.internal.ProducerStage$TransactionProducerStageLogic$$anon$4.onPull(ProducerStage.scala:191)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:486)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] - should commit the current transaction at commit interval *** FAILED *** (164 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnComplete, found OnError(java.lang.IllegalArgumentException: Cannot pull port (messages(1699878757)) twice
[info] 	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:466)
[info] 	at akka.stream.stage.GraphStageLogic.tryPull(GraphStage.scala:480)
[info] 	at akka.kafka.internal.ProducerStage$TransactionProducerStageLogic$$anon$4.onPull(ProducerStage.scala:191)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:486)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[info] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] )
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:414)
[info]   at akka.kafka.internal.ProducerTest.$anonfun$new$57(ProducerTest.scala:369)
[info]   at akka.kafka.test.Utils$.assertAllStagesStopped(Utils.scala:37)
[info]   at akka.kafka.internal.ProducerTest.$anonfun$new$56(ProducerTest.scala:349)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   ...

```

**Comment by seglo** [comment]
@ennru Interesting, is this happening sporadically for you?  I see in the stack trace it happened during `ProducerTest`.

**Comment by ennru** [comment]
Yes, I've seen it on Travis once. Travis is very unpredictable in performance, so it often shows errors not reproducible locally.

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
