### ISSUE TITLE
Failed: TransactionsSpec must complete a consume-transform-produce transaction with transient failure causing an abort with restartable source

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#471]
"must complete a consume-transform-produce transaction with transient failure causing an abort with restartable source"

```
[info] - must complete a consume-transform-produce transaction with transient failure causing an abort with restartable source *** FAILED *** (11 seconds, 808 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:142)
[info]   at akka.kafka.scaladsl.TransactionsSpec.$anonfun$new$10(TransactionsSpec.scala:82)
[info]   at akka.kafka.test.Utils$.assertAllStagesStopped(Utils.scala:37)
```

https://travis-ci.org/akka/reactive-kafka/jobs/383211644

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
