### ISSUE TITLE
Failed: RetentionPeriodSpec must resume from committed offset

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#472]
```
[info] - must resume from committed offset *** FAILED *** (1 minute, 28 seconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(36)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:387)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:387)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
```

https://travis-ci.org/akka/reactive-kafka/jobs/383564332

**Comment by 2m** [comment]
https://travis-ci.org/akka/reactive-kafka/jobs/384718107

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
