### ISSUE TITLE
Failed: Consumer must read from mutiple topics in multiple partitions

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#475]
https://travis-ci.org/akka/reactive-kafka/jobs/383629948

```
[info] Consumer in different consumer groups
[info] - must read all data from multiple topics in multiple partitions *** FAILED *** (10 seconds, 240 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.kafka.scaladsl.MultiConsumerSpec$$anonfun$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$3.apply(MultiConsumerSpec.scala:119)
```

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
