### ISSUE TITLE
Failed: IntegrationSpec must handle commit without demand

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#479]
```
10:39:41.905 WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-9] Error while fetching metadata with correlation id 20 : {topic-1-8=LEADER_NOT_AVAILABLE}
[info] - must handle commit without demand *** FAILED *** (10 seconds, 154 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 10 seconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$22(IntegrationSpec.scala:174)
[info]   at akka.kafka.test.Utils$.assertAllStagesStopped(Utils.scala:31)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$21(IntegrationSpec.scala:156)
```

https://travis-ci.org/akka/reactive-kafka/jobs/384679493

**Comment by ennru** [comment]
We haven't seen any problems with this since improving the tests, closing.
