### ISSUE TITLE
Failed: Transactions benchmark generated a transient failure when pushing produced message downstream

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#484]
I observed this when running the benchmark specs (`akka-transactions`) for the new transactions tests.  I haven't been able to reproduce it.

```
    Benchmarks.run(RunTestCommand("transactions", kafkaHost, 100000))
    Benchmarks.run(RunTestCommand("akka-transactions", kafkaHost, 100000))
```
Stacktrace
```
java.lang.IllegalArgumentException: Cannot push port (result(1687258400)) twice, or before it being pulled
        at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:570)
        at akka.kafka.internal.ProducerStage$DefaultProducerStageLogic.produce(ProducerStage.scala:149)
        at akka.kafka.internal.ProducerStage$DefaultProducerStageLogic$$anon$2.onPush(ProducerStage.scala:109)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by 2m** [comment]
A newer stack trace for this would be:
```
09:10:09.385 ERROR [default-dispatcher-2] akka.actor.RepointableActorRef        Error in stage [akka.kafka.internal.TransactionalProducerStage@b48759d]: Cannot push port (result(1772414947)) twice, or before it being pulled
java.lang.IllegalArgumentException: Cannot push port (result(1772414947)) twice, or before it being pulled
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:570)
	at akka.kafka.internal.DefaultProducerStageLogic.produce(DefaultProducerStage.scala:119)
	at akka.kafka.internal.DefaultProducerStageLogic$$anon$2.onPush(DefaultProducerStage.scala:93)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
```
