### ISSUE TITLE
Failure: PartitionedSourceSpec partitioned source should resume topics with demand

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#601]
```
[info] partitioned source
[info] - should resume topics with demand *** FAILED *** (601 milliseconds)
[info]   Set(topic-1) was not empty (PartitionedSourceSpec.scala:98)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.kafka.internal.PartitionedSourceSpec$$anonfun$1$$anonfun$apply$1.apply(PartitionedSourceSpec.scala:98)
[info]   at akka.kafka.internal.PartitionedSourceSpec$$anonfun$1$$anonfun$apply$1.apply(PartitionedSourceSpec.scala:73)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/439005352

**Comment by ennru** [comment]
I guess this is related to the changes introduced by #597.

**Comment by 2m** [comment]
I do not think so. This particular failure happened before #597 got merged.

**Comment by ennru** [comment]
Ok, I'm on it anyway. It fails locally for me every 10th time...
