### ISSUE TITLE
Failed: PartitionedSourceSpec partitioned source should resume topics with demand

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#611]
https://travis-ci.org/akka/alpakka-kafka/jobs/440658900

```
[info] PartitionedSourceSpec:
[info] partitioned source
[info] - should resume topics with demand *** FAILED *** (430 milliseconds)
[info]   Set(topic-1) was not empty (PartitionedSourceSpec.scala:77)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.kafka.internal.PartitionedSourceSpec$$anonfun$1$$anonfun$apply$1.apply(PartitionedSourceSpec.scala:77)
[info]   at akka.kafka.internal.PartitionedSourceSpec$$anonfun$1$$anonfun$apply$1.apply(PartitionedSourceSpec.scala:52)
```

It seems that #601 does not want to go away quietly.

**Comment by ennru** [comment]
Experiencing it repeatedly today https://travis-ci.org/akka/alpakka-kafka/jobs/449473247

**Comment by ennru** [comment]
See even #601 

It happened again in https://travis-ci.org/akka/alpakka-kafka/jobs/615474265#L439

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/616606436#L539

**Comment by ennru** [comment]
Recent failures are different than the original report:
```
[info] partitioned source
[info] - should resume topics with demand *** FAILED *** (10 seconds, 347 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 10 seconds
```

**Comment by seglo** [comment]
Now on GitHub Actions:

https://github.com/akka/alpakka-kafka/runs/1865861742?check_suite_focus=true#step:6:3181

**Comment by johanandren** [comment]
https://github.com/akka/alpakka-kafka/actions/runs/4721371265/jobs/8374740353?pr=1622#step:6:3202
