### ISSUE TITLE
Failed: ConsumerSpec should complete futures with failure when commit after stop

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#637]
```
[info] - should complete futures with failure when commit after stop *** FAILED *** (10 seconds, 96 milliseconds)
[info]   Expected exception akka.kafka.CommitTimeoutException to be thrown, but java.util.concurrent.TimeoutException was thrown (ConsumerSpec.scala:320)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
[info]   at akka.kafka.internal.ConsumerSpec.newAssertionFailedException(ConsumerSpec.scala:49)
[info]   at org.scalatest.Assertions.intercept(Assertions.scala:812)
[info]   at org.scalatest.Assertions.intercept$(Assertions.scala:802)
[info]   at akka.kafka.internal.ConsumerSpec.intercept(ConsumerSpec.scala:49)
[info]   at akka.kafka.internal.ConsumerSpec.$anonfun$new$43(ConsumerSpec.scala:320)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:28)
[info]   at akka.kafka.internal.ConsumerSpec.$anonfun$new$42(ConsumerSpec.scala:302)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/451836199

**Comment by ennru** [comment]
I see this test fail locally as well now.

**Comment by ennru** [comment]
This hasn't shown very a long time now.
Closing.
