### ISSUE TITLE
Draining Control throws exception when used immediately after stream start

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#668]
Exception is:

```
java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
```

**Comment by 2m** [comment]
https://github.com/akka/alpakka-kafka/pull/665/files#r237763633

**Comment by seglo** [comment]
```
[info] - must access metrics *** FAILED *** (80 milliseconds)
[info]   java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor. To access materializer use Source/Flow/Sink.setup factory
[info]   at akka.stream.stage.GraphStageLogic.interpreter(GraphStage.scala:392)
[info]   at akka.stream.stage.GraphStageLogic.materializer(GraphStage.scala:403)
[info]   at akka.kafka.internal.BaseSingleSourceLogic.executionContext(BaseSingleSourceLogic.scala:35)
[info]   at akka.kafka.internal.MetricsControl$class.metrics(ControlImplementations.scala:88)
[info]   at akka.kafka.internal.BaseSingleSourceLogic.metrics(BaseSingleSourceLogic.scala:25)
[info]   at akka.kafka.scaladsl.IntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$11$$anonfun$apply$24.apply(IntegrationSpec.scala:400)
[info]   at akka.kafka.scaladsl.IntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$11$$anonfun$apply$24.apply(IntegrationSpec.scala:388)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.kafka.scaladsl.IntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$11.apply(IntegrationSpec.scala:388)
[info]   at akka.kafka.scaladsl.IntegrationSpec$$anonfun$2$$anonfun$apply$mcV$sp$11.apply(IntegrationSpec.scala:388)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1075)
[info]   at akka.kafka.tests.scaladsl.LogCapturing$class.withFixture(LogCapturing.scala:57)
[info]   at akka.kafka.scaladsl.SpecBase.withFixture(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1072)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1085)
[info]   at akka.kafka.scaladsl.SpecBase.akka$kafka$Repeated$$super$runTest(SpecBase.scala:15)
[info]   at akka.kafka.Repeated$class.run0$1(Repeated.scala:25)
[info]   at akka.kafka.Repeated$class.runTest(Repeated.scala:29)
[info]   at akka.kafka.scaladsl.SpecBase.runTest(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:393)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:407)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1144)
[info]   at akka.kafka.scaladsl.SpecBase.runTests(SpecBase.scala:15)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1124)
[info]   at akka.kafka.testkit.scaladsl.ScalatestKafkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(ScalatestKafkaSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.kafka.scaladsl.SpecBase.org$scalatest$WordSpecLike$$super$run(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1189)
[info]   at akka.kafka.scaladsl.SpecBase.run(SpecBase.scala:15)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:483)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/625853052#L755
