### ISSUE TITLE
Partitioned source does not shut down cleanly when downstream cancels

### ISSUE THREAD

**Issue by gmethvin** [akka/alpakka-kafka#672]
The current `SubSourceLogic` implementation for the partitioned source does not wait for sub-sources to finish processing before shutting down the consumer. For example, given some code like:

```scala
Consumer.committablePartitionedSource(consumerSettings, subscription)
  .mapAsyncUnordered(MaxConcurrentStreams) { case (_, source) =>
    source
      .mapAsync(1)(somethingThatMightUnexpectedlyThrow)
      .mapAsync(1)(_.commitScaladsl())
      .runWith(Sink.ignore)
  }
  .runWith(Sink.ignore)
```

If `somethingThatMightUnexpectedlyThrow` throws an unexpected exception for one partition, it will cancel the upstream and cause the main source stage to complete. This shuts down the Kafka consumer actor without waiting for the sub-sources to complete, as is noted by this TODO in the code: https://github.com/akka/alpakka-kafka/blob/073ac22/core/src/main/scala/akka/kafka/internal/SubSourceLogic.scala#L261

Since some of the sub-sources may still be running, we may attempt to commit offsets back to Kafka, triggering this exception many times:

```
akka.kafka.CommitTimeoutException: Kafka commit took longer than: 15000 milliseconds
	at akka.kafka.internal.ConsumerStage$KafkaAsyncConsumerCommitterRef$$anonfun$commit$8.applyOrElse(ConsumerStage.scala:142)
	at akka.kafka.internal.ConsumerStage$KafkaAsyncConsumerCommitterRef$$anonfun$commit$8.applyOrElse(ConsumerStage.scala:140)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The message is misleading because the commit didn't actually time out going to Kafka. In my code the `_.commitScaladsl()` is actually wrapped in a retry helper and I see this exception immediately on each retry. I assume this is because the consumer has already shut down and the ask immediately fails.

Ideally, if the downstream cancels for any reason, we should at least attempt to wait for sub-sources to shut down, since they may still have outstanding messages to commit. Otherwise we might lose commits when we don't have to, which could potentially lead to undesirable results.

**Comment by ennru** [comment]
Which Alpakka Kafka version do you use? Partitioned sources inner workings improved quite a bit in 1.0-M1.

**Comment by gmethvin** [comment]
I originally discovered the issue on 0.22, but based on the code it seems like it should also be reproducible on 1.0-M1, though I didn't have a chance to attempt to reproduce. If it's helpful I can create a sample project reproducing on the latest version. In any case the [TODO is still in the code](https://github.com/akka/alpakka-kafka/blob/master/core/src/main/scala/akka/kafka/internal/SubSourceLogic.scala#L261) to shut down the substreams before shutting down the main stage, so I assumed that was good enough evidence that there was an issue in Alpakka Kafka, at least in theory.

**Comment by gmethvin** [comment]
Here's a failing test reproducing the issue: https://github.com/gmethvin/alpakka-kafka/blob/commit-failures/tests/src/test/scala/akka/kafka/scaladsl/PartitionedSourcesSpec.scala#L44. If we fail one of the partition sources, then I would expect the other partition sources to complete and at least attempt to wait for outstanding messages to be committed before the consumer is shut down. Is that a reasonable expectation?

**Comment by ennru** [comment]
Yes, the TODO is still correct and I believe fixing it will solve your issue.
Thank you for the reproducer, I'll look into it.

**Comment by ennru** [comment]
Solving the TODO doesn't help your scenario. The sub-sources can't know when their sub-streams are drained and everything has been committed.
For flat streams the `DrainingControl` solves exactly this scenario, but enabling that for partitioned sources is a major endeavour.

Instead this can be solved by using the `stop-timeout` setting which exists, but is unused right now. The `Stop` message to the `KafkaConsumerActor` can be delayed by `stop-timeout` and thus be used to make sure there is a "good chance" for committing to finish.

**Comment by gmethvin** [comment]
Okay, I think that will probably work for my use case. Thanks.
