### ISSUE TITLE
[Failed] PartitionedSourceFailoverSpec: partitioned source should not lose any...

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#745]
...messages when a Kafka node dies

```
[info] PartitionedSourceFailoverSpec:
[info] partitioned source
[info] - should not lose any messages when a Kafka node dies *** FAILED *** (9 seconds, 703 milliseconds)
[info]   java.lang.Error: Timeout while waiting for desired consumer group state. Tried [10] times, slept [100 milliseconds] in between.
[info]   at akka.kafka.testkit.scaladsl.KafkaSpec.check$1(KafkaSpec.scala:172)
[info]   at akka.kafka.testkit.scaladsl.KafkaSpec.periodicalCheck(KafkaSpec.scala:179)
[info]   at akka.kafka.testkit.scaladsl.KafkaSpec.waitUntilConsumerGroup(KafkaSpec.scala:140)
[info]   at akka.kafka.PartitionedSourceFailoverSpec.$anonfun$new$3(PartitionedSourceFailoverSpec.scala:83)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:30)
[info]   at akka.kafka.PartitionedSourceFailoverSpec.$anonfun$new$2(PartitionedSourceFailoverSpec.scala:46)
```

https://travis-ci.org/akka/alpakka/jobs/505595719#L701

**Comment by ennru** [comment]
Another 
https://travis-ci.org/akka/alpakka-kafka/jobs/505747539#L7898

**Comment by ennru** [comment]
This hasn't shown since a very long while now.
Closing.
