### ISSUE TITLE
Kafka ConfigException Causes An Akka Application To Freeze

### ISSUE THREAD

**Issue by maxstreese** [akka/alpakka-kafka#770]
### Versions used 

```
libraryDependencies += "com.typesafe.akka" %% "akka-stream-kafka" % "1.0.1"

libraryDependencies += "org.apache.logging.log4j" %% "log4j-api-scala" % "11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-api" % "2.11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-1.2-api" % "2.11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-jcl" % "2.11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-slf4j-impl" % "2.11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-jul" % "2.11.0"
libraryDependencies += "org.apache.logging.log4j" % "log4j-core" % "2.11.0"
```

### Expected Behavior

Considering the following application:

```
package de.smarttra.akka.kafka.producer

import akka.actor.ActorSystem
import akka.kafka.ProducerSettings
import akka.kafka.scaladsl.Producer
import akka.stream.{ActorMaterializer, Materializer}
import akka.stream.scaladsl.Source
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.StringSerializer
import org.apache.logging.log4j.scala.Logging
import scala.concurrent.ExecutionContextExecutor
import scala.util.{Failure, Success}

object ProducerApp extends App with Logging {
  implicit val system: ActorSystem = ActorSystem("producer-sample")
  implicit val materializer: Materializer = ActorMaterializer()

  val producerSettings =
    ProducerSettings(system, new StringSerializer, new StringSerializer)

  val topic = "some-topic"
  val key   = "some-key"
  val value = "some-value"

  val producerSink = Producer.plainSink(producerSettings)
  logger.info("XYZ: GOT HERE")

  val producerDone = Source
    .single(new ProducerRecord[String, String](topic, key, value))
    .runWith(producerSink)

  implicit val executionContextExecutor: ExecutionContextExecutor = system.dispatcher
  producerDone onComplete {
    case Success(_) => logger.info("XYZ: DONE"); system.terminate()
    case Failure(e) => logger.fatal(s"XYZ: ${e.toString}"); system.terminate()
  }
}
```

And the following configuration:

```
akka.kafka.producer {
  kafka-clients {
    bootstrap.servers = "this-aint-valid"
  }
}
```

When providing invalid producer configuration I expect this to be handled by alpakka kafka. Either the stream should fail or - depending on configuration - retries should be made.

### Actual Behavior

The future never completes. Instead an uncaught `org.apache.kafka.common.config.ConfigException` in turn causes an uncaught `org.apache.kafka.common.KafkaException` which escapes the future and *blocks* the application leading to it never completing, as can be seen from the logs below.

### Relevant logs

```
[error] (run-main-0) org.apache.kafka.common.KafkaException: Failed to construct kafka producer
[error] org.apache.kafka.common.KafkaException: Failed to construct kafka producer
[error]         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429)
[error]         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:286)
[error]         at akka.kafka.ProducerSettings$.createKafkaProducer(ProducerSettings.scala:151)
[error]         at akka.kafka.ProducerSettings$.$anonfun$apply$3(ProducerSettings.scala:70)
[error]         at akka.kafka.ProducerSettings.createKafkaProducer(ProducerSettings.scala:316)
[error]         at akka.kafka.scaladsl.Producer$.$anonfun$flexiFlow$1(Producer.scala:197)
[error]         at akka.kafka.internal.DefaultProducerStage.createLogic(DefaultProducerStage.scala:37)
[error]         at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:93)
[error]         at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:631)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:451)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:416)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:407)
[error]         at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:588)
[error]         at akka.stream.scaladsl.Source.runWith(Source.scala:103)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$.delayedEndpoint$de$smarttra$akka$kafka$producer$ProducerApp$1(ProducerApp.scala:29)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$delayedInit$body.apply(ProducerApp.scala:15)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$.main(ProducerApp.scala:15)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp.main(ProducerApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: this-aint-valid
[error]         at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:56)
[error]         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:407)
[error]         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:286)
[error]         at akka.kafka.ProducerSettings$.createKafkaProducer(ProducerSettings.scala:151)
[error]         at akka.kafka.ProducerSettings$.$anonfun$apply$3(ProducerSettings.scala:70)
[error]         at akka.kafka.ProducerSettings.createKafkaProducer(ProducerSettings.scala:316)
[error]         at akka.kafka.scaladsl.Producer$.$anonfun$flexiFlow$1(Producer.scala:197)
[error]         at akka.kafka.internal.DefaultProducerStage.createLogic(DefaultProducerStage.scala:37)
[error]         at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:93)
[error]         at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:631)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:451)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:416)
[error]         at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:407)
[error]         at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:588)
[error]         at akka.stream.scaladsl.Source.runWith(Source.scala:103)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$.delayedEndpoint$de$smarttra$akka$kafka$producer$ProducerApp$1(ProducerApp.scala:29)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$delayedInit$body.apply(ProducerApp.scala:15)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp$.main(ProducerApp.scala:15)
[error]         at de.smarttra.akka.kafka.producer.ProducerApp.main(ProducerApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

Please note that at the end of the logs the application is still running and not terminated.

**Comment by maxstreese** [comment]
I should add that I am very new to all of this so in case I did overlook something very obvious I apologize and hope for a hint. I did however follow examples closely and therefore do not see where I made a wrong turn.

**Comment by maxstreese** [comment]
Update: The same goes for `org.apache.kafka.common.errors.TimeoutException`. So I guess no exceptions are caught by the future approach?

**Comment by ennru** [comment]
@maxstreese Thank you for the detailed description of your problem.

This exception is hit when the `KafkaProducer` instance is created during materialization of the stream. The `Future` is never created and the JVM thread is ended with the exception.

Your problem is that the Actor system doesn't shut down on this error. You may wrap the thing in try/catch and terminate it upon failure.

**Comment by ennru** [comment]
As you didn't come back on this, I assume you solved it.
Closing.

**Comment by maxstreese** [comment]
Firstly: Likewise thanks for the detailed response!

We solved it for now by wrapping the `runWith` Future in another Future and then combining them. I do not think its a particularly nice solution but it works for now.

Cheers! :beers:
