### ISSUE TITLE
[Failure] TransactionsSpec: must complete with messages filtered out and transient failure causing an abort with restartable source

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#826]
```
[info] TransactionsSpec:
[info] A consume-transform-produce cycle
[info] - must complete with messages filtered out and transient failure causing an abort with restartable source *** FAILED *** (14 seconds, 419 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(51)
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:395)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:395)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.$anonfun$expectNextN$1(StreamTestKit.scala:411)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:941)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:411)
[info]   at akka.kafka.scaladsl.TransactionsSpec.$anonfun$new$17(TransactionsSpec.scala:199)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.kafka.scaladsl.TransactionsSpec.$anonfun$new$16(TransactionsSpec.scala:148)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/544581914#L1823

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/601873942#L455

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/615297999#L468

**Comment by seglo** [comment]
Still happening with increased timefactor

https://travis-ci.org/akka/alpakka-kafka/jobs/625749137#L476

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/640314579#L465

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/640635810#L1385 in #1026

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/648052161#L446 in master

**Comment by seglo** [comment]
Hopefully resolved with #1048

**Comment by seglo** [comment]
Observed a timeout with this test again, at a new point.

```
[info]   java.lang.AssertionError: assertion failed: timeout (100 seconds) during expectMsg while waiting for OnNext(1)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:418)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:395)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:411)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:411)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:411)
[info]   at akka.kafka.scaladsl.TransactionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$16.apply(TransactionsSpec.scala:197)
[info]   at akka.kafka.scaladsl.TransactionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$16.apply(TransactionsSpec.scala:146)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.kafka.scaladsl.TransactionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(TransactionsSpec.scala:146)
[info]   at akka.kafka.scaladsl.TransactionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(TransactionsSpec.scala:146)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1075)
[info]   at akka.kafka.tests.scaladsl.LogCapturing$class.withFixture(LogCapturing.scala:57)
[info]   at akka.kafka.scaladsl.SpecBase.withFixture(SpecBase.scala:15)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1072)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1085)
[info]   at akka.kafka.scaladsl.SpecBase.akka$kafka$Repeated$$super$runTest(SpecBase.scala:15)
[info]   at akka.kafka.Repeated$class.run0$1(Repeated.scala:25)
```

https://travis-ci.org/github/akka/alpakka-kafka/jobs/685724245#L1069
