### ISSUE TITLE
Failed IntegrationSpec must signal rebalance events to actor

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#832]
```
[info] - must signal rebalance events to actor *** FAILED *** (37 seconds, 646 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 61 times, sleeping 500000000 nanoseconds between each query. (IntegrationSpec.scala:120)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$6(IntegrationSpec.scala:120)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.kafka.scaladsl.IntegrationSpec.$anonfun$new$5(IntegrationSpec.scala:52)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/547197965

**Comment by ennru** [comment]
Not all messages are received for some reason
https://travis-ci.org/akka/alpakka-kafka/jobs/580201215#L890
