### ISSUE TITLE
[Failed] ReconnectSpec: A Consumer must continue to work when there is another Kafka port available 

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#842]
```
[info]   List("138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200") was not equal to Vector("101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200") (ReconnectSpec.scala:195)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
[info]   at akka.kafka.scaladsl.ReconnectSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$5.apply(ReconnectSpec.scala:195)
[info]   at akka.kafka.scaladsl.ReconnectSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$5.apply(ReconnectSpec.scala:165)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/552865756#L1372

**Comment by ennru** [comment]
No failures reported after this.
Closing.
