### ISSUE TITLE
[Failure] CommittingSpec: Multiple consumers to one committer...

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#957]
...must merge multiple consumers` offsets for different partitions (#942) 

```
[info] Multiple consumers to one committer
[info] - must merge multiple consumers` offsets for different partitions (#942) *** FAILED *** (19 seconds, 660 milliseconds)
[info]   The future returned an exception of type: akka.kafka.CommitTimeoutException, with message: Kafka commit took longer than: 15 seconds. (CommittingSpec.scala:459)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.kafka.scaladsl.CommittingSpec.$anonfun$new$44(CommittingSpec.scala:459)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
```

**Comment by nikkatalnikov** [comment]
we got this error with `committablePartitionedSource`.
any progress on it?

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/619520795#L556

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/625389283#L983 in #1005 
https://travis-ci.org/akka/alpakka-kafka/jobs/625389285#L986 in #1005

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/625607991#L978 in #926

**Comment by ennru** [comment]
I'm trying to understand how this can be a 15s timeout https://travis-ci.org/akka/alpakka-kafka/jobs/625654499#L979-L982

**Comment by ennru** [comment]
It is indeed that the first consumer actor is terminated before the commit message is sent to it. This is the scenario where it is important to have a `stop-timeout` which is large enough to keep the actor around after downstream completed.

**Comment by seglo** [comment]
Hopefully, this is resolved in #1007, but I'll keep the issue open for the time being.
