### ISSUE TITLE
[Failure] RetentionPeriodSpec: must resume from committed offset

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#979]
New since #975?

```
RetentionPeriodSpec:
After retention period (1 min) consumer
- must resume from committed offset *** FAILED *** (1 second, 718 milliseconds)
  java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnError (OnError(org.apache.kafka.common.errors.InconsistentGroupProtocolException: The group member's supported protocols are incompatible with those of existing members or first group member tried to join with empty protocol type or empty protocol list.
))
  at scala.Predef$.assert(Predef.scala:223)
  at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:529)
  at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:500)
  at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:499)
  at akka.testkit.TestKit.expectMsgType(TestKit.scala:923)
  at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:398)
  at akka.kafka.scaladsl.RetentionPeriodSpec.$anonfun$new$3(RetentionPeriodSpec.scala:64)
  at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
  at akka.kafka.scaladsl.RetentionPeriodSpec.$anonfun$new$2(RetentionPeriodSpec.scala:41)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/615474262#L643

**Comment by seglo** [comment]
Could it be related to the mismatch in broker and client version in the test?  It's strange that this would be a transient issue.

**Comment by seglo** [comment]
https://travis-ci.org/akka/alpakka-kafka/jobs/649001181#L667

**Comment by seglo** [comment]
https://travis-ci.org/github/akka/alpakka-kafka/jobs/685687861#L652
