### ISSUE TITLE
[Failure] Producer should abort the current transaction on failure 

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#980]
```ProducerSpec:
Producer
 - should abort the current transaction on failure *** FAILED *** (32 milliseconds)
  org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
kafkaProducer.abortTransaction();
-> at akka.kafka.internal.ProducerMock.verifyTxAbort(ProducerSpec.scala:607)
Actually, there were zero interactions with this mock.
  at akka.kafka.internal.ProducerMock.verifyTxAbort(ProducerSpec.scala:607)
  at akka.kafka.internal.ProducerSpec.$anonfun$new$80(ProducerSpec.scala:511)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

https://travis-ci.org/akka/alpakka-kafka/jobs/615474266#L556

**Comment by ennru** [comment]
This hasn't been noticed ever since it seems.
Closing.
